=== chemaar/moldeas2/doc/phd/phd-doc/memoria-full/examples/events.xsd
<?xml version="1.0" encoding="iso-8859-1"?>
<xs:schema xmlns="http://purl.org/weso/events" 
	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	xmlns:xhtml="http://www.w3.org/1999/xhtml" 
	targetNamespace="http://purl.org/weso/events" 
	elementFormDefault="qualified" attributeFormDefault="unqualified">

<xs:import namespace="http://www.w3.org/1999/xhtml" 
	schemaLocation="http://www.w3.org/2002/08/xhtml/xhtml1-strict.xsd"/>	
	<xs:simpleType name="customString">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="255"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="customDate">
		<xs:restriction base="xs:string">
			<xs:pattern value="([0-9]{2,2}/){2,2}([0-9]{4,4})"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="categories">
		<xs:restriction base="xs:NMTOKEN">
			<xs:enumeration value="family"/>
			<xs:enumeration value="master"/>
			<xs:enumeration value="work"/>
			<xs:enumeration value="other"/>
		</xs:restriction>
	</xs:simpleType>
				
	<xs:complexType name="event">		
		<xs:sequence>
			<xs:element name="title" type="customString" minOccurs="1" maxOccurs="1"/>
			<xs:element name="date" type="customDate" minOccurs="1" maxOccurs="1"/>		
			<xs:element name="start" type="xs:time" minOccurs="1" maxOccurs="1"/>
			<xs:element name="end" type="xs:time" minOccurs="0" maxOccurs="1"/>
			<xs:element name="place" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="persons" type="personsType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="description" type="descriptionType" minOccurs="1" maxOccurs="1"/>				
		</xs:sequence>
		<xs:attribute name="type" type="categories" use="required"/>
	</xs:complexType>
	...
		
	<xs:element name="events">		
		<xs:complexType>
			<xs:sequence>
				<xs:element name="event" type="event" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== chemaar/moldeas2/doc/phd/phd-doc/memoria/examples/events.xml
<?xml version="1.0" encoding="utf-8"?>
<events xmlns="http://purl.org/weso/events" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://purl.org/weso/events events.xsd">
	<event type="family">
		<title>Bautizo</title>
		<date>28/10/2011</date>
		<start>12:00:00</start>
		<place>Tapia de Casariego</place>
		<description>
			Bautizo de <xhtml:em>Pablo</xhtml:em> en 
<xhtml:a href="http://maps.google.com/maps" title="Tapia de Casariego">Tapia de Casariego</xhtml:a>. 
		</description>		
	</event>
	<event type="work">
		<title>Seguimiento</title>
		<date>04/11/2010</date>
		<start>10:00:00</start>
		<end>13:00:00</end>
		<place>Facultad de Ciencias, Oviedo</place>
		<persons>
			<person>Chema</person>
		</persons>
		<description>
			Kick-off de 10ders.
		</description>
	</event>	
</events>
